-- Inserir 50 registros na tabela associados
INSERT INTO associados (nome, sobrenome, idade, email) VALUES
('João', 'Silva', 30, 'joao.silva@example.com'),
('Maria', 'Oliveira', 28, 'maria.oliveira@example.com'),
('Pedro', 'Santos', 35, 'pedro.santos@example.com'),
('Ana', 'Souza', 26, 'ana.souza@example.com'),
('Carlos', 'Lima', 40, 'carlos.lima@example.com'),
('Juliana', 'Almeida', 32, 'juliana.almeida@example.com'),
('Ricardo', 'Pereira', 38, 'ricardo.pereira@example.com'),
('Fernanda', 'Costa', 27, 'fernanda.costa@example.com'),
('Paulo', 'Ferreira', 45, 'paulo.ferreira@example.com'),
('Aline', 'Ribeiro', 29, 'aline.ribeiro@example.com'),
('Lucas', 'Martins', 33, 'lucas.martins@example.com'),
('Camila', 'Barbosa', 25, 'camila.barbosa@example.com'),
('Vinícius', 'Gomes', 36, 'vinicius.gomes@example.com'),
('Bianca', 'Carvalho', 31, 'bianca.carvalho@example.com'),
('Felipe', 'Araújo', 42, 'felipe.araujo@example.com'),
('Larissa', 'Melo', 24, 'larissa.melo@example.com'),
('Tiago', 'Farias', 37, 'tiago.farias@example.com'),
('Vanessa', 'Correia', 34, 'vanessa.correia@example.com'),
('Renato', 'Nogueira', 41, 'renato.nogueira@example.com'),
('Mariana', 'Batista', 30, 'mariana.batista@example.com'),
('Guilherme', 'Teixeira', 28, 'guilherme.teixeira@example.com'),
('Thaís', 'Monteiro', 27, 'thais.monteiro@example.com'),
('André', 'Rocha', 35, 'andre.rocha@example.com'),
('Natália', 'Dias', 26, 'natalia.dias@example.com'),
('Leandro', 'Pinto', 39, 'leandro.pinto@example.com'),
('Patrícia', 'Nascimento', 32, 'patricia.nascimento@example.com'),
('Rodrigo', 'Rezende', 33, 'rodrigo.rezende@example.com'),
('Júlia', 'Fonseca', 31, 'julia.fonseca@example.com'),
('Eduardo', 'Vieira', 36, 'eduardo.vieira@example.com'),
('Priscila', 'Lopes', 25, 'priscila.lopes@example.com'),
('Diego', 'Barros', 37, 'diego.barros@example.com'),
('Amanda', 'Campos', 29, 'amanda.campos@example.com'),
('Fábio', 'Freitas', 40, 'fabio.freitas@example.com'),
('Roberta', 'Antunes', 28, 'roberta.antunes@example.com'),
('Sérgio', 'Morais', 45, 'sergio.morais@example.com'),
('Tatiana', 'Cardoso', 26, 'tatiana.cardoso@example.com'),
('Marcelo', 'Moura', 41, 'marcelo.moura@example.com'),
('Luana', 'Xavier', 27, 'luana.xavier@example.com'),
('Rafael', 'Silveira', 38, 'rafael.silveira@example.com'),
('Isabela', 'Siqueira', 34, 'isabela.siqueira@example.com'),
('Maurício', 'Machado', 42, 'mauricio.machado@example.com'),
('Carla', 'Fernandes', 29, 'carla.fernandes@example.com'),
('Bruno', 'Tavares', 33, 'bruno.tavares@example.com'),
('Daniele', 'Castro', 31, 'daniele.castro@example.com'),
('José', 'Moreira', 30, 'jose.moreira@example.com'),
('Helena', 'Mendes', 25, 'helena.mendes@example.com'),
('Rogério', 'Campos', 35, 'rogerio.campos@example.com'),
('Manuela', 'Aguiar', 28, 'manuela.aguiar@example.com'),
('Cláudio', 'Guimarães', 39, 'claudio.guimaraes@example.com'),
('Sofia', 'Borges', 24, 'sofia.borges@example.com'),
('Augusto', 'Andrade', 37, 'augusto.andrade@example.com');


select * from associados a 
